site_name: apksearch
site_author: Abhi
site_description: apksearch Documentation
copyright: Copyright © 2024 Abhi
repo_url: https://github.com/AbhiTheModder/apksearch

theme:
  name: material
  features:
    - navigation.tracking
    - content.code.copy
    - navigation.instant
  palette:
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: blue-grey
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  font:
    text: Roboto Mono
    code: Fira Code

plugins:
  - autorefs
  - offline
  - search
  - mkdocstrings:
      handlers:
        python:
          load_external_modules: true
          options:
            show_bases: true
  - glightbox

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Home: index.md
  - Development:
      - API Reference: api.md

